services:
  app:
    build:
      context: .
    restart: "no"
    image: ghcr.io/bakkerme/ai-new-processor:latest
    container_name: anp-app
    environment:
      - ANP_CRON_SCHEDULE=${ANP_CRON_SCHEDULE}
      - ANP_LLM_URL=${ANP_LLM_URL}
      - ANP_LLM_API_KEY=${ANP_LLM_API_KEY}
      - ANP_LLM_MODEL=${ANP_LLM_MODEL}
      - ANP_EMAIL_TO=${ANP_EMAIL_TO}
      - ANP_EMAIL_FROM=${ANP_EMAIL_FROM}
      - ANP_EMAIL_HOST=${ANP_EMAIL_HOST}
      - ANP_EMAIL_PORT=${ANP_EMAIL_PORT}
      - ANP_EMAIL_USERNAME=${ANP_EMAIL_USERNAME}
      - ANP_EMAIL_PASSWORD=${ANP_EMAIL_PASSWORD}
